### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by omerasif57** [theMladyPan/coodise#6]
**Describe the bug**
I started the server using `python manage.py runserver` and had `invalid syntax error`

**To Reproduce**
1. create python 3.4 environment
2. install django
3. install django-bootstrap, django-bootstrap3 and django-crispy-forms
4. python manage.py runserver

File "..\coodise-devel\coodise-devel\coodise\urls.py", line 19, in <module>
    from .views import main
  File "..\coodise-devel\coodise-devel\coodise\views\main.py", line 118
    messages.success(request, f"{item_to_delete} successfully deleted.")
                                                                      ^
SyntaxError: invalid syntax

**Comment by theMladyPan** [comment]
Hi

Thank you for your issue. Sorry for late reply. The coodise is written acc to python 3.6 standart which I should have mentioned.

Please try it with python 3.6.
